#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    #true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "nil"
    statusline_inactive_separator = "bar"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = false
    statusline_unicode_symbols = false
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = true

    enable_neomake = false
    enable_ale = true
    relativenumber = false
# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "cycle"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "checkers"

[[layers]]
  name = "debug"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lsp"
  filetypes = [
    "haskell",
    "c",
    "cpp",
    "python"
  ]
  [layers.override_cmd]
    haskell = ['hie', '--lsp']
    c = ['clangd-6.0']
    cpp = ['clangd-6.0']


[[layers]]
  name = "debug"

[[layers]]
  name = "shell"
  default_shell = "terminal"
  default_position = "bottom"
